# Generated by Django 5.1 on 2024-08-24 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('career', '진로'), ('health', '건강'), ('relationship', '인간 관계'), ('money', '돈'), ('goal', '목표'), ('study', '학업/성적'), ('etc', '기타')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_confirm', models.CharField(choices=[('pending', '보류됨'), ('approved', '승인됨'), ('rejected', '거절됨')], default='pending', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('wish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wishes.wish')),
            ],
        ),
    ]
